export const LIKE_POST = 'LIKE_POST';
export const SAVE_POST = 'SAVE_POST';
export const DELETE_POST = 'DELETE_POST';
export const EDIT_POST = 'EDIT_POST';
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';

export const SHOW_POST_LIKES_BAR = 'SHOW_POST_LIKES_BAR';
export const SHOW_COMMENTS_LIKES_BAR = 'SHOW_COMMENTS_LIKES_BAR';
export const UPDATE_LIKES_COUNT_INCREMENT = 'UPDATE_LIKES_COUNT_INCREMENT';
export const UPDATE_LIKES_COUNT_DECREMENT = 'UPDATE_LIKES_COUNT_DECREMENT';
export const REFRESH_LIKES_LIST = 'REFRESH_LIKES_LIST';
export const UPDATE_LIKES_COUNT_INCREMENT_POST = 'UPDATE_LIKES_COUNT_INCREMENT_POST';
export const UPDATE_LIKES_COUNT_DECREMENT_POST = 'UPDATE_LIKES_COUNT_DECREMENT_POST';

export const NEW_POST = 'NEW_POST';
export const POST_EDITED_SUCCESSFULLY = 'POST_EDITED_SUCCESSFULLY';

export const LENGTH_BELOW_MINIMUM = 'The description should have atleast 200 characters';
export const FILE_OUTSIDE_LIMITS_VIDEO = 'File must be shorter than 10 mins and within 200MB';
export const FILE_OUTSIDE_LIMITS_PDF = 'File must be shorter than 8MB';
